version: '3.8'
services:

  # Nginx-PHP Webstack Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "9090:80"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network


  #Mongo Service
  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: clara123
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
